<a href="https://colab.research.google.com/github/GioGio2004/pytorch/blob/main/00_pytorch_first_steps_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as ps
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.2.1+cu121


## creating tensors
### intruduction to tensors


In [2]:
2+2

4

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.item()

7

In [5]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector[1]

tensor(7)

In [7]:
MATRIX = torch.tensor([[1, 2], [3, 4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [8]:
MATRIX[1]

tensor([3, 4])

In [9]:
TENSOR = torch.tensor([[[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9,]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

creating randon tensor


In [10]:
random_tensor = torch.rand(3 , 4 )
random_tensor

tensor([[0.8544, 0.4556, 0.6427, 0.0676],
        [0.2165, 0.0575, 0.4265, 0.9325],
        [0.4463, 0.4136, 0.0676, 0.5059]])

In [11]:
random_tensor.ndim

2

In [12]:
rand_size_image_tensor = torch.rand(size=(244, 244, 3))
rand_size_image_tensor.shape, rand_size_image_tensor.ndim

(torch.Size([244, 244, 3]), 3)

In [13]:
tensor_of_zeros = torch.zeros(3, 4)
tensor_of_zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [14]:
new_tensor = tensor_of_zeros* random_tensor
new_tensor


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [15]:
torch.arange(1, 11)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])